project:
  type: website
  output-dir: docs

website:
  title: "SE Gyges Blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/segyges
      - icon: twitter
        href: https://twitter.com/segyges
format:
  html:
    theme: slate
    css: styles.css



